### ISSUE TITLE
'POS' must be added to the pipeline before adding 'MLHybrid'.

### ISSUE THREAD

**Issue by sirago** [BMDSoftware/neji#10] opened 2017-02-22 23:52 UTC
After much trial and error I finally got it to a place where I can load the frontend and see my list of annotations. I'm stuck on this, when I click Annotate Text:

Caused by: pt.ua.tm.neji.exception.NejiException: The specified module 'MLHybrid' requires 'POS', which were not provided by earlier modules in the pipeline. A module or a corpus that provides 'POS' must be added to the pipeline before adding 'MLHybrid'.

Any ideas?

I'm running "./nejiWeb.sh -t 5"

**Comment by davidcampos** [comment] 2017-02-23 19:37
@sirago 
The problem is that the ML module requires POS tags and only tokenization is being performed by the NLP module. Using "neji.sh" you can specify the parsing level through the "-plvl" option. Can you try performing the annotation using this script and option?

**Comment by davidcampos** [comment] 2017-04-24 15:13
@sirago 
Since no further feedback was provided, I am going to close this issue.

**Closed by davidcampos** 2017-04-24 15:13 UTC
